from сравнение_элементов import содержит
from терминал import печать

def тест_содержит():
    варианты = [
        ["что пустое - ошибка", "", "компьютер", False, "ошибка"],
        ["где пустое - ошибка", "что", "",False, "ошибка"],
        ["что неизвестный тип - ошибка", {}, "компьютер",False,"ошибка"],
        ["где неизвестный тип - ошибка", "что", {},False,"ошибка"],
        ["в списке что не стр - ошибка", [1],"где",False,"ошибка"],
        ["в списке где не стр - ошибка", "что", [1],False,"ошибка"],

        # название - что ищем - где ищем - игнорировать регистр - ожидаемый ответ
        ["строка - строка - содержит - регистр важен","а","абв", False, True],
        ["строка - строка - содержит - игнор регистра","А","абв", True, True],
        ["строка - строка - не содержит - регистр важен","А","абв", False, False],
        ["список - список - содержит - регистр важен",["А", "б"], ["АБВ", "где"], False, True],
        ["список - список - содержит - игнор регистра",["а", "б"], ["АБВ", "где"],True, True],
        ["список - список - не содержит - регистр важен", ["А", "б"], ["аБВ", "где"], False, False],
        ["список - строка - содержит - регистр важен",  ["А", "б"], "АБВ", False, True],
        ["список - строка - содержит - игнор регистра",["а", "б"], "АБВ", True, True],
        ["список - строка - не содержит - регистр важен",["А", "Б"],"абв", False, False],
        ["строка - список - содержит - регистр важен","а",["абв", "где"], False, True],
        ["строка - список - содержит - игнор регистра","А",["абв", "где"], True, True],
        ["строка - список - не содержит - регистр важен","А",["абв", "где"], False, False],
    ]

    пройдено = 0
    for вариант in варианты:
        название, что, где, регистр, правильный_ответ = вариант


        try:
            # в блок try записываются строки, которые могут вызвать ошибк, но нельзя в этом месте оюрывать выполнение кода из-за неё
            ответ = содержит(что, где, регистр)
        except:
            # в блок except (переводится как "исключение") код зайдёт только тогда, когда в try произошла ошибка
            ответ = "ошибка"    
        if ответ == правильный_ответ:
            пройдено += 1
            печать(название, цвет_зелёный=True)
        else:
            печать(название, цвет_красный=True)

    print(f'пройдено {пройдено}')


if __name__ == "__main__":
    тест_содержит()
    